# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/fuzzystrmatch/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/fuzzystrmatch
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = fuzzystrmatch
DATA_built = fuzzystrmatch.sql
DOCS = README.fuzzystrmatch README.soundex

include $(top_srcdir)/contrib/contrib-global.mk
