// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/DefinitionKind:1.0
//
final public class DefinitionKindHolder implements org.omg.CORBA.portable.Streamable
{
    public DefinitionKind value;

    public
    DefinitionKindHolder()
    {
    }

    public
    DefinitionKindHolder(DefinitionKind initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DefinitionKindHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DefinitionKindHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DefinitionKindHelper.type();
    }
}
