// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/DomainManager:1.0
//
/***/

public interface DomainManagerOperations
{
    //
    // IDL:omg.org/CORBA/DomainManager/get_domain_policy:1.0
    //
    /***/

    Policy
    get_domain_policy(int policy_type);
}
