// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/ExcDescriptionSeq:1.0
//
final public class ExcDescriptionSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public ExceptionDescription[] value;

    public
    ExcDescriptionSeqHolder()
    {
    }

    public
    ExcDescriptionSeqHolder(ExceptionDescription[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ExcDescriptionSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ExcDescriptionSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ExcDescriptionSeqHelper.type();
    }
}
