// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/InterfaceDef:1.0
//
final public class InterfaceDefHolder implements org.omg.CORBA.portable.Streamable
{
    public InterfaceDef value;

    public
    InterfaceDefHolder()
    {
    }

    public
    InterfaceDefHolder(InterfaceDef initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = InterfaceDefHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        InterfaceDefHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return InterfaceDefHelper.type();
    }
}
