// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/OperationDef:1.0
//
/***/

public interface OperationDefOperations extends ContainedOperations
{
    //
    // IDL:omg.org/CORBA/OperationDef/result:1.0
    //
    /***/

    org.omg.CORBA.TypeCode
    result();

    //
    // IDL:omg.org/CORBA/OperationDef/result_def:1.0
    //
    /***/

    IDLType
    result_def();

    void
    result_def(IDLType val);

    //
    // IDL:omg.org/CORBA/OperationDef/params:1.0
    //
    /***/

    ParameterDescription[]
    params();

    void
    params(ParameterDescription[] val);

    //
    // IDL:omg.org/CORBA/OperationDef/mode:1.0
    //
    /***/

    OperationMode
    mode();

    void
    mode(OperationMode val);

    //
    // IDL:omg.org/CORBA/OperationDef/contexts:1.0
    //
    /***/

    String[]
    contexts();

    void
    contexts(String[] val);

    //
    // IDL:omg.org/CORBA/OperationDef/exceptions:1.0
    //
    /***/

    ExceptionDef[]
    exceptions();

    void
    exceptions(ExceptionDef[] val);
}
