// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/OperationDescription:1.0
//
/***/

final public class OperationDescription implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _star_id = "IDL:omg.org/CORBA/OperationDescription:1.0";

    public
    OperationDescription()
    {
    }

    public
    OperationDescription(String name,
                         String id,
                         String defined_in,
                         String version,
                         org.omg.CORBA.TypeCode result,
                         OperationMode mode,
                         String[] contexts,
                         ParameterDescription[] parameters,
                         ExceptionDescription[] exceptions)
    {
        this.name = name;
        this.id = id;
        this.defined_in = defined_in;
        this.version = version;
        this.result = result;
        this.mode = mode;
        this.contexts = contexts;
        this.parameters = parameters;
        this.exceptions = exceptions;
    }

    public String name;
    public String id;
    public String defined_in;
    public String version;
    public org.omg.CORBA.TypeCode result;
    public OperationMode mode;
    public String[] contexts;
    public ParameterDescription[] parameters;
    public ExceptionDescription[] exceptions;
}
