// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/PolicyManager:1.0
//
/***/

public interface PolicyManagerOperations
{
    //
    // IDL:omg.org/CORBA/PolicyManager/get_policy_override:1.0
    //
    /***/

    Policy
    get_policy_override(int t);

    //
    // IDL:omg.org/CORBA/PolicyManager/get_specific_policy_overrides:1.0
    //
    /***/

    Policy[]
    get_specific_policy_overrides(int[] ts);

    //
    // IDL:omg.org/CORBA/PolicyManager/get_all_policy_overrides:1.0
    //
    /***/

    Policy[]
    get_all_policy_overrides();

    //
    // IDL:omg.org/CORBA/PolicyManager/add_policy_overrides:1.0
    //
    /***/

    void
    add_policy_overrides(Policy[] policies)
        throws bank.CORBA.PolicyManagerPackage.InvalidPolicies;

    //
    // IDL:omg.org/CORBA/PolicyManager/remove_policy_overrides:1.0
    //
    /***/

    void
    remove_policy_overrides(int[] ts);

    //
    // IDL:omg.org/CORBA/PolicyManager/replace_all_policy_overrides:1.0
    //
    /***/

    void
    replace_all_policy_overrides(Policy[] policies)
        throws bank.CORBA.PolicyManagerPackage.InvalidPolicies;
}
