// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/PolicyTypeSeq:1.0
//
final public class PolicyTypeSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public int[] value;

    public
    PolicyTypeSeqHolder()
    {
    }

    public
    PolicyTypeSeqHolder(int[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PolicyTypeSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PolicyTypeSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PolicyTypeSeqHelper.type();
    }
}
