// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/Repository:1.0
//
/***/

public interface Repository extends RepositoryOperations,
                                    Container,
                                    org.omg.CORBA.portable.IDLEntity
{
}
