// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/SequenceDef:1.0
//
/***/

public interface SequenceDef extends SequenceDefOperations,
                                     IDLType,
                                     org.omg.CORBA.portable.IDLEntity
{
}
