// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/StructMember:1.0
//
/***/

final public class StructMember implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _star_id = "IDL:omg.org/CORBA/StructMember:1.0";

    public
    StructMember()
    {
    }

    public
    StructMember(String name,
                 org.omg.CORBA.TypeCode type,
                 IDLType type_def)
    {
        this.name = name;
        this.type = type;
        this.type_def = type_def;
    }

    public String name;
    public org.omg.CORBA.TypeCode type;
    public IDLType type_def;
}
