// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/StructMemberSeq:1.0
//
final public class StructMemberSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public StructMember[] value;

    public
    StructMemberSeqHolder()
    {
    }

    public
    StructMemberSeqHolder(StructMember[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = StructMemberSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        StructMemberSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return StructMemberSeqHelper.type();
    }
}
