// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA;

//
// IDL:omg.org/CORBA/WrongTransaction:1.0
//
/***/

final public class WrongTransaction extends org.omg.CORBA.UserException
{
    private static final String _star_id = "IDL:omg.org/CORBA/WrongTransaction:1.0";

    public
    WrongTransaction()
    {
        super(_star_id);
    }

    public
    WrongTransaction(String _reason)
    {
        super(_star_id + " " + _reason);
    }
}
