# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/lo/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/lo
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = lo
DATA_built = lo.sql
DATA = lo_drop.sql lo_test.sql
DOCS = README.lo

include $(top_srcdir)/contrib/contrib-global.mk
