# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/rtree_gist/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/rtree_gist
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = rtree_gist
DATA_built = rtree_gist.sql
DOCS = README.rtree_gist
REGRESS = rtree_gist

include $(top_srcdir)/contrib/contrib-global.mk
