// **********************************************************************
//
// Copyright (c) 2002-2003 
// StarMiddleware.net	
// www.StarMiddleware.net
// 
// All Rights Reserved
//
// Author: Ren Yi	starots@sohu.com	
// **********************************************************************

// Version: 1.0.0

#pragma prefix "implicit"

interface Account
{
    void connect();
    
    void close();
    
    void sum();

    void deposit();

    void withdraw();

};
