# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/intarray/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/intarray
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = _int
DATA_built = _int.sql
DOCS = README.intarray
REGRESS = _int

include $(top_srcdir)/contrib/contrib-global.mk
