// **********************************************************************
//
// Copyright (c) 2001-2004
// StarMiddleware.net
// www.StarMiddleware.net
//
// All Rights Reserved
//
// Author: Huang Jie    huangjie@email.com
// Author: Wang Kebo    mep@263.net
// Author: Su Liang     centuryfree@yahoo.com.cn
//
// **********************************************************************

// Version: 1.0.0

#ifndef __CCMCommon_idl__
#define __CCMCommon_idl__

//Modified by WangKeBo for compilation on TAO
#ifdef TAO
#include "ForTAO.idl"
//#include <orb.idl>
#else
#include <orb.idl>
#endif

/*
module CORBA
{

    typedef string RepositoryId;

    interface IRObject;

    typedef sequence<octet> OctetSeq;
};
*/

#pragma prefix "omg.org"

module Components
{
	typedef unsigned long FailureReason;

	exception InvalidConfiguration { };

	typedef string FeatureName;

	typedef sequence<FeatureName> NameList;

	exception WrongComponentType { };

	exception DuplicateKeyValue { };

	exception InvalidKey { };

	exception UnknownKeyValue { };

	exception FinderFailure
	{
		FailureReason reason;
	};

	abstract valuetype PrimaryKeyBase { };

	valuetype Cookie
	{
		private CORBA::OctetSeq cookieValue;
	};

	// Required here but defined in Chapter 62

	enum CCMExceptionReason
	{
		SYSTEM_ERROR,
		CREATE_ERROR,
		REMOVE_ERROR,
		DUPLICATE_KEY,
		FIND_ERROR,
		OBJECT_NOT_FOUND,
		NO_SUCH_ENTITY
	};

	exception CCMException
	{
		CCMExceptionReason reason;
	};

	//add by wsf 2004.6.29
	valuetype ConfigValue
	{
		public FeatureName name;
		public any value;
	};
	typedef sequence<ConfigValue> ConfigValues;
	
	typedef sequence<Object> ObjectSeq;
	//end by wsf 2004.6.29
};

#endif