// **********************************************************************
//
// Copyright (c) 2001-2004
// StarMiddleware.net
// www.StarMiddleware.net
//
// All Rights Reserved
//
// Author: Huang Jie    huangjie@email.com
// Author: Wang Kebo    mep@263.net
// Author: Su Liang     centuryfree@yahoo.com.cn
//
// **********************************************************************

// Version: 1.0.0

#ifndef __CCMHome_idl__
#define __CCMHome_idl__

#include "CCMCommon.idl"

#pragma prefix "omg.org"

module Components
{
	
	interface CCMObject;

	exception CreateFailure
	{
		FailureReason reason;
	};

	exception RemoveFailure
	{
		FailureReason reason;
	};

	interface CCMHome
	{
		CORBA::IRObject get_component_def();

		CORBA::IRObject get_home_def ();

		void remove_component (in CCMObject comp)
			raises (RemoveFailure);
	};

	interface KeylessCCMHome
	{
		CCMObject create_component() 
			raises (CreateFailure);
	};
};

#endif