// **********************************************************************
//
// Copyright (c) 2001-2004
// StarMiddleware.net
// www.StarMiddleware.net
//
// All Rights Reserved
//
// Author: Huang Jie    huangjie@email.com
// Author: Wang Kebo    mep@263.net
// Author: Su Liang     centuryfree@yahoo.com.cn
//
// **********************************************************************

// Version: 1.0.0

#ifndef __CCMEJBean_idl__
#define __CCMEJBean_idl__

#include <CCMObject.idl>

#pragma prefix "omg.org"

module Components
{	
	// From Chapter 64: Integrating with Enterprise JavaBeans
	abstract valuetype Enumeration
	{
       		boolean has_more_elements();

		CCMObject next_element();
	};

	typedef sequence<CCMObject> CCMObjectSeq;

	valuetype DefaultEnumeration : Enumeration
	{
		private CCMObjectSeq objects;
	};
};

#endif