// **********************************************************************
//
// Copyright (c) 2001-2004
// StarMiddleware.net
// www.StarMiddleware.net
//
// All Rights Reserved
//
// Author: Huang Jie    huangjie@email.com
// Author: Wang Kebo    mep@263.net
// Author: Su Liang     centuryfree@yahoo.com.cn
//
// **********************************************************************

// Version: 1.0.0

#ifndef __OMG_ORB_idl__
#define __OMG_ORB_idl__

#ifdef ORBacus
#include <OB/orb.idl>
#endif

#ifdef StarBus
#include <STAR/orb.idl>
#endif

#endif