# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/string/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/string
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = string_io
DATA_built = string_io.sql
DOCS = README.string_io

include $(top_srcdir)/contrib/contrib-global.mk
