// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA.InterfaceDefPackage;

//
// IDL:omg.org/CORBA/InterfaceDef/FullInterfaceDescription:1.0
//
final public class FullInterfaceDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
    public FullInterfaceDescription value;

    public
    FullInterfaceDescriptionHolder()
    {
    }

    public
    FullInterfaceDescriptionHolder(FullInterfaceDescription initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = FullInterfaceDescriptionHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        FullInterfaceDescriptionHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return FullInterfaceDescriptionHelper.type();
    }
}
