// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.CORBA.InterfaceDefPackage;

//
// IDL:omg.org/CORBA/InterfaceDef/FullInterfaceDescription:1.0
//
/***/

final public class FullInterfaceDescription implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _star_id = "IDL:omg.org/CORBA/InterfaceDef/FullInterfaceDescription:1.0";

    public
    FullInterfaceDescription()
    {
    }

    public
    FullInterfaceDescription(String name,
                             String id,
                             String defined_in,
                             String version,
                             bank.CORBA.OperationDescription[] operations,
                             bank.CORBA.AttributeDescription[] attributes,
                             String[] base_interfaces,
                             org.omg.CORBA.TypeCode type)
    {
        this.name = name;
        this.id = id;
        this.defined_in = defined_in;
        this.version = version;
        this.operations = operations;
        this.attributes = attributes;
        this.base_interfaces = base_interfaces;
        this.type = type;
    }

    public String name;
    public String id;
    public String defined_in;
    public String version;
    public bank.CORBA.OperationDescription[] operations;
    public bank.CORBA.AttributeDescription[] attributes;
    public String[] base_interfaces;
    public org.omg.CORBA.TypeCode type;
}
