# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/pg_logger/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/pg_logger
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

PROGRAM = pg_logger
OBJS	= pg_logger.o

DOCS = README.pg_logger

include $(top_srcdir)/contrib/contrib-global.mk
