// **********************************************************************
//
// Generated by the CIDL Translator
//
// Copyright (c) 2001-2004
// StarMiddleware Group
// www.StarMiddleware.net
//
// All Rights Reserved
//
// Author: Huang Jie        huangjie@email.com
// Author: Chang Junsheng   cjs7908@163.com
// Author: Zhen Xianrong
//
// **********************************************************************

#include <CORBA.h>
#include <CCM_DepositComp_impl.h>

#ifdef HAVE_STD_IOSTREAM
using namespace std;
#endif

Bank::DepositCompComposition::CCM_DepositComp_impl::CCM_DepositComp_impl()
{
}

Bank::DepositCompComposition::CCM_DepositComp_impl::~CCM_DepositComp_impl()
{
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::configuration_complete()
	throw (Components::InvalidConfiguration, CORBA::SystemException)
{
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::enter_dyn_deploy()
	throw(CORBA::SystemException)
{
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::leave_dyn_deploy()
	throw(CORBA::SystemException)
{
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::set_session_context(Components::SessionContext* ctx)
    throw(Components::CCMException,
          CORBA::SystemException)
{
    #ifdef TAO
    ctx_ = Bank::CCM_DepositComp_Context::_duplicate(dynamic_cast<Bank::CCM_DepositComp_Context*>(ctx));
    #else
    ctx_ = Bank::CCM_DepositComp_Context::_narrow(ctx);
    #endif
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::ccm_activate()
    throw(Components::CCMException,
          CORBA::SystemException)
{
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::ccm_passivate()
    throw(Components::CCMException,
          CORBA::SystemException)
{
}

void
Bank::DepositCompComposition::CCM_DepositComp_impl::ccm_remove()
    throw(Components::CCMException,
          CORBA::SystemException)
{
}


void
Bank::DepositCompComposition::CCM_DepositComp_impl::deposit(const char* id,
                                                            CORBA::ULong amount)
    throw(CORBA::SystemException)
{
    Bank::AccountOp_var a = ctx_ -> get_connection_the_account();
    a -> deposit(id, amount);
}

Bank::DepositCompComposition::CCM_DepositCompHome_impl::CCM_DepositCompHome_impl()
{
}

Bank::DepositCompComposition::CCM_DepositCompHome_impl::~CCM_DepositCompHome_impl()
{
}

Components::EnterpriseComponent_ptr
Bank::DepositCompComposition::CCM_DepositCompHome_impl::create()
    throw(Components::CCMException,
          CORBA::SystemException)
{
    return new Bank::DepositCompComposition::CCM_DepositComp_impl();
}

char*
Bank::DepositCompComposition::CCM_DepositCompHome_impl::get_storage_home_id()
{
    return 0;
}

