# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/miscutil/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/miscutil
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = misc_utils
DATA_built = misc_utils.sql
DOCS = README.misc_utils

include $(top_srcdir)/contrib/contrib-global.mk
