# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/btree_gist/Makefile,v 1.2 2004/07/05 08:55:02 SuLiang Exp $

subdir = contrib/btree_gist
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = btree_gist
DATA_built = btree_gist.sql
DOCS = README.btree_gist
REGRESS = btree_gist

include $(top_srcdir)/contrib/contrib-global.mk
