# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/chkpass/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/chkpass
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = chkpass
DATA_built = chkpass.sql
DOCS = README.chkpass

include $(top_srcdir)/contrib/contrib-global.mk
