# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/userlock/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/userlock
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = user_locks
DATA_built = user_locks.sql
DOCS = README.user_locks

include $(top_srcdir)/contrib/contrib-global.mk
