// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/ComputeOp:1.0
//
final public class ComputeOpHolder implements org.omg.CORBA.portable.Streamable
{
    public ComputeOp value;

    public
    ComputeOpHolder()
    {
    }

    public
    ComputeOpHolder(ComputeOp initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ComputeOpHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ComputeOpHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ComputeOpHelper.type();
    }
}
