// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/Delegation:1.0
//
/***/

public interface DelegationOperations extends bank.Components.CCMObjectOperations
{
    //
    // IDL:Bank/Delegation/provide_delegation_Op:1.0
    //
    /***/

    DelegationOp
    provide_delegation_Op();

    //
    // IDL:Bank/Delegation/connect_deposit:1.0
    //
    /***/

    void
    connect_deposit(DepositOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Delegation/disconnect_deposit:1.0
    //
    /***/

    DepositOp
    disconnect_deposit()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Delegation/get_connection_deposit:1.0
    //
    /***/

    DepositOp
    get_connection_deposit();

    //
    // IDL:Bank/Delegation/connect_withdraw:1.0
    //
    /***/

    void
    connect_withdraw(WithdrawOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Delegation/disconnect_withdraw:1.0
    //
    /***/

    WithdrawOp
    disconnect_withdraw()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Delegation/get_connection_withdraw:1.0
    //
    /***/

    WithdrawOp
    get_connection_withdraw();
}
