// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/DepositComp:1.0
//
/***/

public interface DepositComp extends DepositCompOperations,
                                     bank.Components.CCMObject,
                                     org.omg.CORBA.portable.IDLEntity
{
}
