// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/InterestComputer:1.0
//
/***/

public interface InterestComputerOperations extends bank.Components.CCMObjectOperations
{
    //
    // IDL:Bank/InterestComputer/provide_compute_op:1.0
    //
    /***/

    ComputeOp
    provide_compute_op();
}
