// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/Manager:1.0
//
/***/

public interface ManagerOperations extends bank.Components.CCMObjectOperations
{
    //
    // IDL:Bank/Manager/provide_manager_op:1.0
    //
    /***/

    ManagerOp
    provide_manager_op();

    //
    // IDL:Bank/Manager/connect_deposit:1.0
    //
    /***/

    void
    connect_deposit(DepositOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Manager/disconnect_deposit:1.0
    //
    /***/

    DepositOp
    disconnect_deposit()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Manager/get_connection_deposit:1.0
    //
    /***/

    DepositOp
    get_connection_deposit();

    //
    // IDL:Bank/Manager/connect_withdraw:1.0
    //
    /***/

    void
    connect_withdraw(WithdrawOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Manager/disconnect_withdraw:1.0
    //
    /***/

    WithdrawOp
    disconnect_withdraw()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Manager/get_connection_withdraw:1.0
    //
    /***/

    WithdrawOp
    get_connection_withdraw();

    //
    // IDL:Bank/Manager/connect_query:1.0
    //
    /***/

    void
    connect_query(QueryOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Manager/disconnect_query:1.0
    //
    /***/

    QueryOp
    disconnect_query()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Manager/get_connection_query:1.0
    //
    /***/

    QueryOp
    get_connection_query();

    //
    // IDL:Bank/Manager/connect_authenticator:1.0
    //
    /***/

    void
    connect_authenticator(AuthenticationOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Manager/disconnect_authenticator:1.0
    //
    /***/

    AuthenticationOp
    disconnect_authenticator()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Manager/get_connection_authenticator:1.0
    //
    /***/

    AuthenticationOp
    get_connection_authenticator();

    //
    // IDL:Bank/Manager/connect_openAccount:1.0
    //
    /***/

    void
    connect_openAccount(OpenAccountOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Manager/disconnect_openAccount:1.0
    //
    /***/

    OpenAccountOp
    disconnect_openAccount()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Manager/get_connection_openAccount:1.0
    //
    /***/

    OpenAccountOp
    get_connection_openAccount();

    //
    // IDL:Bank/Manager/connect_delAccount:1.0
    //
    /***/

    void
    connect_delAccount(DelAccountOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/Manager/disconnect_delAccount:1.0
    //
    /***/

    DelAccountOp
    disconnect_delAccount()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/Manager/get_connection_delAccount:1.0
    //
    /***/

    DelAccountOp
    get_connection_delAccount();
}
