// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/ManagerOp:1.0
//
final public class ManagerOpHolder implements org.omg.CORBA.portable.Streamable
{
    public ManagerOp value;

    public
    ManagerOpHolder()
    {
    }

    public
    ManagerOpHolder(ManagerOp initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ManagerOpHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ManagerOpHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ManagerOpHelper.type();
    }
}
