// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/OpenAccountComp:1.0
//
/***/

public interface OpenAccountCompOperations extends bank.Components.CCMObjectOperations
{
    //
    // IDL:Bank/OpenAccountComp/provide_open_account_op:1.0
    //
    /***/

    OpenAccountOp
    provide_open_account_op();
}
