// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/QueryCompHomeImplicit:1.0
//
/***/

public interface QueryCompHomeImplicitOperations extends bank.Components.KeylessCCMHomeOperations
{
    //
    // IDL:Bank/QueryCompHomeImplicit/create:1.0
    //
    /***/

    QueryComp
    create()
        throws bank.Components.CreateFailure;
}
