// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/WithdrawComp:1.0
//
/***/

public interface WithdrawCompOperations extends bank.Components.CCMObjectOperations
{
    //
    // IDL:Bank/WithdrawComp/provide_withdraw_op:1.0
    //
    /***/

    WithdrawOp
    provide_withdraw_op();

    //
    // IDL:Bank/WithdrawComp/connect_the_account:1.0
    //
    /***/

    void
    connect_the_account(AccountOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/WithdrawComp/disconnect_the_account:1.0
    //
    /***/

    AccountOp
    disconnect_the_account()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/WithdrawComp/get_connection_the_account:1.0
    //
    /***/

    AccountOp
    get_connection_the_account();

    //
    // IDL:Bank/WithdrawComp/connect_interest_computer:1.0
    //
    /***/

    void
    connect_interest_computer(ComputeOp conn)
        throws bank.Components.AlreadyConnected,
               bank.Components.InvalidConnection;

    //
    // IDL:Bank/WithdrawComp/disconnect_interest_computer:1.0
    //
    /***/

    ComputeOp
    disconnect_interest_computer()
        throws bank.Components.NoConnection;

    //
    // IDL:Bank/WithdrawComp/get_connection_interest_computer:1.0
    //
    /***/

    ComputeOp
    get_connection_interest_computer();
}
