// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/WithdrawCompHomeExplicit:1.0
//
final public class WithdrawCompHomeExplicitHolder implements org.omg.CORBA.portable.Streamable
{
    public WithdrawCompHomeExplicit value;

    public
    WithdrawCompHomeExplicitHolder()
    {
    }

    public
    WithdrawCompHomeExplicitHolder(WithdrawCompHomeExplicit initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = WithdrawCompHomeExplicitHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        WithdrawCompHomeExplicitHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return WithdrawCompHomeExplicitHelper.type();
    }
}
