// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Bank;

//
// IDL:Bank/WithdrawCompHomeExplicit:1.0
//
/***/

public interface WithdrawCompHomeExplicit extends WithdrawCompHomeExplicitOperations,
                                                  bank.Components.HomeConfiguration,
                                                  org.omg.CORBA.portable.IDLEntity
{
}
