# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/array/Makefile,v 1.2 2004/07/05 08:55:02 SuLiang Exp $

subdir = contrib/array
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = array_iterator
DATA_built = array_iterator.sql
DOCS = README.array_iterator

include $(top_srcdir)/contrib/contrib-global.mk
