# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/fulltextindex/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/fulltextindex
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = fti
DATA_built = fti.sql
DOCS = README.fti
SCRIPTS = fti.pl

include $(top_srcdir)/contrib/contrib-global.mk
