// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/ConnectType:1.0
//
/***/

public class ConnectType implements org.omg.CORBA.portable.IDLEntity
{
    private static ConnectType [] values_ = new ConnectType[5];
    private int value_;

    public final static int _PROVIDES = 0;
    public final static ConnectType PROVIDES = new ConnectType(_PROVIDES);
    public final static int _COMPONENTSUPPORTEDINTERFACE = 1;
    public final static ConnectType COMPONENTSUPPORTEDINTERFACE = new ConnectType(_COMPONENTSUPPORTEDINTERFACE);
    public final static int _HOMEINTERFACE = 2;
    public final static ConnectType HOMEINTERFACE = new ConnectType(_HOMEINTERFACE);
    public final static int _EMITS = 3;
    public final static ConnectType EMITS = new ConnectType(_EMITS);
    public final static int _PUBLISHES = 4;
    public final static ConnectType PUBLISHES = new ConnectType(_PUBLISHES);

    protected
    ConnectType(int value)
    {
        values_[value] = this;
        value_ = value;
    }

    public int
    value()
    {
        return value_;
    }

    public static ConnectType
    from_int(int value)
    {
        if(value < values_.length)
            return values_[value];
        else
            throw new org.omg.CORBA.BAD_PARAM("Value (" + value  + ") out of range", 25, org.omg.CORBA.CompletionStatus.COMPLETED_NO);
    }

    private java.lang.Object
    readResolve()
        throws java.io.ObjectStreamException
    {
        return from_int(value());
    }
}
