// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/ConnectType:1.0
//
final public class ConnectTypeHelper
{
    public static void
    insert(org.omg.CORBA.Any any, ConnectType val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static ConnectType
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            String[] members = new String[5];
            members[0] = "PROVIDES";
            members[1] = "COMPONENTSUPPORTEDINTERFACE";
            members[2] = "HOMEINTERFACE";
            members[3] = "EMITS";
            members[4] = "PUBLISHES";
            typeCode_ = orb.create_enum_tc(id(), "ConnectType", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:omg.org/Components/ConnectType:1.0";
    }

    public static ConnectType
    read(org.omg.CORBA.portable.InputStream in)
    {
        ConnectType _star_v;
        _star_v = ConnectType.from_int(in.read_ulong());
        return _star_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, ConnectType val)
    {
        out.write_ulong(val.value());
    }
}
