// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/CookieRequired:1.0
//
final public class CookieRequiredHolder implements org.omg.CORBA.portable.Streamable
{
    public CookieRequired value;

    public
    CookieRequiredHolder()
    {
    }

    public
    CookieRequiredHolder(CookieRequired initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CookieRequiredHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CookieRequiredHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CookieRequiredHelper.type();
    }
}
