// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/DynamicConnectInfo:1.0
//
final public class DynamicConnectInfoHelper
{
    public static void
    insert(org.omg.CORBA.Any any, DynamicConnectInfo val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static DynamicConnectInfo
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[4];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "portIdentifier";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "connectPortType";
            members[1].type = ConnectTypeHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "connectToRef";
            members[2].type = orb.create_interface_tc("IDL:omg.org/CORBA/Object:1.0", "Object");

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "eventSourcePortIdentifier";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            typeCode_ = orb.create_struct_tc(id(), "DynamicConnectInfo", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:omg.org/Components/DynamicConnectInfo:1.0";
    }

    public static DynamicConnectInfo
    read(org.omg.CORBA.portable.InputStream in)
    {
        DynamicConnectInfo _star_v = new DynamicConnectInfo();
        _star_v.portIdentifier = in.read_string();
        _star_v.connectPortType = ConnectTypeHelper.read(in);
        _star_v.connectToRef = in.read_Object();
        _star_v.eventSourcePortIdentifier = in.read_string();
        return _star_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, DynamicConnectInfo val)
    {
        out.write_string(val.portIdentifier);
        ConnectTypeHelper.write(out, val.connectPortType);
        out.write_Object(val.connectToRef);
        out.write_string(val.eventSourcePortIdentifier);
    }
}
