// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/EmitterDescriptions:1.0
//
final public class EmitterDescriptionsHolder implements org.omg.CORBA.portable.Streamable
{
    public EmitterDescription[] value;

    public
    EmitterDescriptionsHolder()
    {
    }

    public
    EmitterDescriptionsHolder(EmitterDescription[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = EmitterDescriptionsHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        EmitterDescriptionsHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return EmitterDescriptionsHelper.type();
    }
}
