// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/Events:1.0
//
/***/

public interface EventsOperations
{
    //
    // IDL:omg.org/Components/Events/get_consumer:1.0
    //
    /***/

    EventConsumerBase
    get_consumer(String sink_name)
        throws InvalidName;

    //
    // IDL:omg.org/Components/Events/subscribe:1.0
    //
    /***/

    Cookie
    subscribe(String publisher_name,
              EventConsumerBase subscriber)
        throws InvalidName,
               InvalidConnection,
               ExceededConnectionLimit;

    //
    // IDL:omg.org/Components/Events/unsubscribe:1.0
    //
    /***/

    void
    unsubscribe(String publisher_name,
                Cookie ck)
        throws InvalidName,
               InvalidConnection;

    //
    // IDL:omg.org/Components/Events/connect_consumer:1.0
    //
    /***/

    void
    connect_consumer(String emitter_name,
                     EventConsumerBase consumer)
        throws InvalidName,
               AlreadyConnected,
               InvalidConnection;

    //
    // IDL:omg.org/Components/Events/disconnect_consumer:1.0
    //
    /***/

    EventConsumerBase
    disconnect_consumer(String source_name)
        throws InvalidName,
               NoConnection;

    //
    // IDL:omg.org/Components/Events/get_all_consumers:1.0
    //
    /***/

    ConsumerDescription[]
    get_all_consumers();

    //
    // IDL:omg.org/Components/Events/get_named_consumers:1.0
    //
    /***/

    ConsumerDescription[]
    get_named_consumers(String[] names)
        throws InvalidName;

    //
    // IDL:omg.org/Components/Events/get_all_emitters:1.0
    //
    /***/

    EmitterDescription[]
    get_all_emitters();

    //
    // IDL:omg.org/Components/Events/get_named_emitters:1.0
    //
    /***/

    EmitterDescription[]
    get_named_emitters(String[] names)
        throws InvalidName;

    //
    // IDL:omg.org/Components/Events/get_all_publishers:1.0
    //
    /***/

    PublisherDescription[]
    get_all_publishers();

    //
    // IDL:omg.org/Components/Events/get_named_publishers:1.0
    //
    /***/

    PublisherDescription[]
    get_named_publishers(String[] names)
        throws InvalidName;
}
