// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/FacetDescriptions:1.0
//
final public class FacetDescriptionsHolder implements org.omg.CORBA.portable.Streamable
{
    public FacetDescription[] value;

    public
    FacetDescriptionsHolder()
    {
    }

    public
    FacetDescriptionsHolder(FacetDescription[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = FacetDescriptionsHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        FacetDescriptionsHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return FacetDescriptionsHelper.type();
    }
}
