// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/HomeConfiguration:1.0
//
/***/

public interface HomeConfiguration extends HomeConfigurationOperations,
                                           CCMHome,
                                           org.omg.CORBA.portable.IDLEntity
{
}
