// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/HomeFinder:1.0
//
final public class HomeFinderHolder implements org.omg.CORBA.portable.Streamable
{
    public HomeFinder value;

    public
    HomeFinderHolder()
    {
    }

    public
    HomeFinderHolder(HomeFinder initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = HomeFinderHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        HomeFinderHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return HomeFinderHelper.type();
    }
}
