// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/PortDescription:1.0
//
/***/

public abstract class PortDescription implements org.omg.CORBA.portable.StreamableValue
{
    //
    // IDL:omg.org/Components/PortDescription/name:1.0
    //
    /***/

    public String name;

    //
    // IDL:omg.org/Components/PortDescription/type_id:1.0
    //
    /***/

    public String type_id;

    private static String[] _STAR_truncatableIds_ =
    {
        PortDescriptionHelper.id()
    };

    public String[]
    _truncatable_ids()
    {
        return _STAR_truncatableIds_;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        name = FeatureNameHelper.read(in);
        type_id = bank.CORBA.RepositoryIdHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        FeatureNameHelper.write(out, name);
        bank.CORBA.RepositoryIdHelper.write(out, type_id);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PortDescriptionHelper.type();
    }
}
