// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/PublisherDescription:1.0
//
final public class PublisherDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
    public PublisherDescription value;

    public
    PublisherDescriptionHolder()
    {
    }

    public
    PublisherDescriptionHolder(PublisherDescription initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PublisherDescriptionHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PublisherDescriptionHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PublisherDescriptionHelper.type();
    }
}
