// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/PublisherDescriptions:1.0
//
final public class PublisherDescriptionsHolder implements org.omg.CORBA.portable.Streamable
{
    public PublisherDescription[] value;

    public
    PublisherDescriptionsHolder()
    {
    }

    public
    PublisherDescriptionsHolder(PublisherDescription[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PublisherDescriptionsHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PublisherDescriptionsHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PublisherDescriptionsHelper.type();
    }
}
