// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/ReceptacleDescriptions:1.0
//
final public class ReceptacleDescriptionsHolder implements org.omg.CORBA.portable.Streamable
{
    public ReceptacleDescription[] value;

    public
    ReceptacleDescriptionsHolder()
    {
    }

    public
    ReceptacleDescriptionsHolder(ReceptacleDescription[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ReceptacleDescriptionsHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ReceptacleDescriptionsHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ReceptacleDescriptionsHelper.type();
    }
}
