// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/ReceptacleDescription:1.0
//
final public class ReceptacleDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
    public ReceptacleDescription value;

    public
    ReceptacleDescriptionHolder()
    {
    }

    public
    ReceptacleDescriptionHolder(ReceptacleDescription initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ReceptacleDescriptionHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ReceptacleDescriptionHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ReceptacleDescriptionHelper.type();
    }
}
