// **********************************************************************
//
// This File Is Automatically Generated by the InterBus IDL-to-Java Compiler !
//
// Copyright (c) 2003
// Intervision Software Co., Ltd.
// Haidian District, Beijing.
//
// All Rights Reserved
//
// **********************************************************************

// Version: 5.0a

package bank.Components;

//
// IDL:omg.org/Components/RemoveFailure:1.0
//
/***/

final public class RemoveFailure extends org.omg.CORBA.UserException
{
    private static final String _star_id = "IDL:omg.org/Components/RemoveFailure:1.0";

    public
    RemoveFailure()
    {
        super(_star_id);
    }

    public
    RemoveFailure(int reason)
    {
        super(_star_id);
        this.reason = reason;
    }

    public
    RemoveFailure(String _reason,
                  int reason)
    {
        super(_star_id + " " + _reason);
        this.reason = reason;
    }

    public int reason;
}
