#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /home/hjcvs/OB-CCM-1.0/postgresql/src/test/Makefile,v 1.2 2004/07/05 08:56:18 SuLiang Exp $
#
#-------------------------------------------------------------------------

.DEFAULT:
	$(MAKE) -C regress $@
