# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/tips/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/tips
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

DOCS = README.apachelog

include $(top_srcdir)/contrib/contrib-global.mk
