# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/earthdistance/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/earthdistance
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = earthdistance
DATA_built = earthdistance.sql
DOCS = README.earthdistance

include $(top_srcdir)/contrib/contrib-global.mk
