# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/noupdate/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/noupdate
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = noup
DATA_built = noup.sql
DOCS = README.noup

include $(top_srcdir)/contrib/contrib-global.mk
