# $Header: /home/hjcvs/OB-CCM-1.0/postgresql/contrib/isbn_issn/Makefile,v 1.2 2004/07/05 08:55:03 SuLiang Exp $

subdir = contrib/isbn_issn
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = isbn_issn
DATA_built = isbn_issn.sql
DOCS = README.isbn_issn

include $(top_srcdir)/contrib/contrib-global.mk
