// *************************************************************************
//
// This File Is Automatically Generated by the StarBusIDL-to-C++ Compiler !
//
// Copyright (c) 2003
// Network Information Security Institute,Computer College,NUDT.
// ChangSha,Hunan,PRC
//
// All Rights Reserved
//
// *************************************************************************

// Version: 5.0.0

#include <STAR/CORBAClient.h>
#include <STAR/CORBAServer.h>
#include <CosTransactionsPolicyType.h>

namespace CosTransactions
{

STAR::TypeCodeConst _tc_InvocationPolicyValue(
"0134f5771500000058000000010000002e00000049444c3a436f735472616e73616374696f6e7"
"32f496e766f636174696f6e506f6c69637956616c75653a312e3000ff0f16000000496e766f63"
"6174696f6e506f6c69637956616c756500201004000000"
);

STAR::TypeCodeConst _tc_OTSPolicyValue(
"0134f5771500000048000000010000002700000049444c3a436f735472616e73616374696f6e7"
"32f4f5453506f6c69637956616c75653a312e3000750f0000004f5453506f6c69637956616c75"
"65006904000000"
);

STAR::TypeCodeConst _tc_NonTxTargetPolicyValue(
"0134f5771500000058000000010000002f00000049444c3a436f735472616e73616374696f6e7"
"32f4e6f6e5478546172676574506f6c69637956616c75653a312e300050170000004e6f6e5478"
"546172676574506f6c69637956616c7565001004000000"
);

} // End of namespace CosTransactions
