// *************************************************************************
//
// This File Is Automatically Generated by the StarBusIDL-to-C++ Compiler !
//
// Copyright (c) 2003
// Network Information Security Institute,Computer College,NUDT.
// ChangSha,Hunan,PRC
//
// All Rights Reserved
//
// *************************************************************************

// Version: 5.0.0

#ifndef ___CosTransactions_skel_h__
#define ___CosTransactions_skel_h__

#include <CosTransactions.h>
#include <STAR/SkelForServerRequest.h>

#include <CosTransactionsOTS_skel.h>
#include <CosTransactionsCurrent_skel.h>
#include <PostgreSQLResource_skel.h>
#include <CosTransactionsUser_skel.h>

#endif
